all:	

Problem1:	problem1.cpp
	g++ -g -std=c++17 -o problem1 problem1.cpp
	
Problem2:	problem2.cpp
	g++ -g -std=c++17 -o problem2 problem2.cpp

Problem3:	problem3.cpp
	g++ -g -std=c++17 -o problem3 problem3.cpp

Problem4:	problem4.cpp
	g++ -g -std=c++17 -o problem4 problem4.cpp

Problem5:	problem5.cpp
	g++ -g -std=c++17 -o problem5 problem5.cpp

Problem6:	problem6.cpp
	g++ -g -std=c++17 -o problem6 problem6.cpp
