Default:

Problem1:	problem1.cpp
	g++ -g problem1.cpp -o problem1.out -lMyFLTK -lfltk -lfltk_images	
Problem2:	problem2.cpp
	g++ -g problem2.cpp -o problem2.out -lMyFLTK -lfltk -lfltk_images
Problem3:	problem3.cpp
	 g++ -g problem3.cpp -o problem3.out -lMyFLTK -lfltk -lfltk_images
Problem4:	problem4.cpp
	 g++ -g problem4.cpp -o problem4.out -lMyFLTK -lfltk -lfltk_images
Problem5:	problem5.cpp
	 g++ -g problem5.cpp -o problem5.out -lMyFLTK -lfltk -lfltk_images
