Problem1:	concatinate.cpp 
	g++ -std=c++17 -ggdb concatinate.cpp -o Problem1

Problem2:	store_temps.cpp
	g++ -std=c++17 -ggdb store_temps.cpp -o Problem2	

Problem3:	temp_stats.cpp
	g++ -std=c++17 -ggdb temp_stats.cpp -o Problem3	

Problem4:	concatinate.cpp
	g++ -std=c++17 -ggdb concatinate.cpp -o Problem4

Problem5:	merge.cpp
	g++ -std=c++17 -ggdb merge.cpp -o Problem5	
