Problem1:	concatinate.cpp 
	g++ -std=c++17 -ggdb concatinate.cpp -o Problem1

Problem2:	store_temps.cpp
	g++ -std=c++17 -ggdb store_temps.cpp -o Problem2	

Problem3:	temp_stats.cpp
	

Problem4:	summation.cpp
	

Problem5:	merge.cpp
	
