Problem1:	concatinate.cpp 
	g++ -std=c++17 -g concatinate.cpp -o Problem1

Problem2:	store_temps.cpp
	g++ -std=c++17 -g store_temps.cpp -o Problem2	

Problem3:	temp_stats.cpp
	g++ -std=c++17 -g temp_stats.cpp -o Problem3	

Problem4:	concatinate.cpp
	g++ -std=c++17 -g concatinate.cpp -o Problem4

Problem5:	merge.cpp
	g++ -std=c++17 -g merge.cpp -o Problem5	
