# Leave default empty
default:

# Make sure to link with fltk library
# Make sure to add debug flag
# compiled files should end with ".out"

Problem1:	


Problem2:


Problem3:


Problem4:


Problem5:


Problem6:


clean:	
	rm -f *.o *.out
