# Leave default empty
default:

# Make sure to link with fltk library
# Make sure to add debug flag
# compiled files should end with ".out"

Problem1:	
	g++ -g problem1.cpp -o problem1.out -lMyFLTK -lfltk -lfltk_images	

Problem2:
	 g++ -g problem2.cpp -o problem2.out -lMyFLTK -lfltk -lfltk_images

Problem3:
	 g++ -g problem3.cpp -o problem3.out -lMyFLTK -lfltk -lfltk_images

Problem4:
	 g++ -g problem4.cpp -o problem4.out -lMyFLTK -lfltk -lfltk_images

Problem5:
	g++ -g problem5.cpp -o problem5.out -lMyFLTK -lfltk -lfltk_images

Problem6:
	g++ -g problem6.cpp -o problem6.out -lMyFLTK -lfltk -lfltk_images

clean:	
	rm -f *.o *.out
